declare module 'three/examples/jsm/loaders/MMDLoader'
declare module 'three/examples/jsm/postprocessing/EffectComposer'
declare module 'three/examples/jsm/postprocessing/RenderPass'
declare module 'three/examples/jsm/postprocessing/ShaderPass'
declare module 'three/examples/jsm/postprocessing/OutlinePass'
declare module 'three/examples/jsm/shaders/BrightnessContrastShader'
declare module 'three/examples/jsm/animation/MMDAnimationHelper'
